---
- name: Install "pm2" node.js package.
  become: yes
  npm:
    name: pm2
    global: yes

- name: Set some variable
  set_fact:
    release_path: "{{ project_path }}/releases/{{ lookup('pipe','date +%Y%m%d%H%M%S') }}"
    current_path: '{{ project_path }}/current'
    app_path: '{{ project_path }}/current/server-side/site'

- name: Create new folder
  become: yes
  file:
    dest: '{{ release_path }}'
    mode: 0755
    recurse: yes
    state: directory

- name: Copy production files
  become: yes
  unarchive:
    src: '{{ project_path }}/current.tar.gz'
    dest: '{{ release_path }}/'
    extra_opts: [--strip-components=1]

- name: Update symlink
  become: yes
  file:
    src: '{{ release_path }}'
    dest: '{{ current_path }}'
    state: link

- name: Delete old pm2 process
  command: pm2 kill
  ignore_errors: yes

- name: Start pm2
  command: pm2 start server.js --name checkbox-app
  args:
    chdir: '{{ app_path }}'

- name: Save service settings
  command: pm2 save
  become: true
  args:
    chdir: '{{ app_path }}'

- name: Copy nginx default file
  become: yes
  copy:
    src: '{{ current_path }}/local-conf/default'
    remote_src: yes
    dest: /etc/nginx/sites-available/
    owner: root
    group: root

- name: Copy nginx.conf file
  become: yes
  copy:
    src: '{{ current_path }}/local-conf/nginx.conf'
    remote_src: yes
    dest: /etc/nginx/
    owner: root
    group: root

- name: Edit the root location
  become: yes
  lineinfile:
    dest: /etc/nginx/sites-available/default
    regexp: 'root \/.*'
    line: '  root {{ current_path }}/public_html;'

- name: Restart nginx
  become: yes
  systemd:
    name: nginx
    state: restarted
