# Playbook to handle pipeline deploy checkbox.io
- hosts: checkbox
  vars:
    project_path: /var/www/nodejs
  vars_files:
    - /bakerx/pipeline/vars/vars.yml
    - /bakerx/pipeline/vars/secrets.yml
  roles:
    - setup_nodejs
    - setup_mongodb
    - setup_nginx
    - deploy_checkbox.io
