# Configure build environment for iTrust and checkbox.io
- hosts: localhost
  vars_files:
    - /bakerx/pipeline/vars/vars.yml
    - /bakerx/pipeline/vars/secrets.yml
  roles:
    - setup_nodejs
    - setup_java
    - setup_mysql
    - setup_iTrust_build_env
