# Main playbook that runs the 'Configure jenkins server task'
# We need to install dependencies first
# And set up env variables first

- hosts: jenkins
  vars_files:
   - /bakerx/pipeline/vars/vars.yml
  roles:
    - setup_nodejs
    - setup_mongodb
    - setup_nginx
    - jenkins
    - setup_build_job
