---

- name: Add java repo
  become: yes
  apt_repository: repo='ppa:openjdk-r/ppa' 

- name: apt update
  become: yes
  apt:
    upgrade: yes
    update_cache: yes

- name: install openjdk
  become: yes
  apt:
    name: openjdk-8-jdk
    state: present

- name: Adding Apt Key For Jenkins
  become: yes
  apt_key:
    url: "https://jenkins-ci.org/debian/jenkins-ci.org.key"
    state: present
    validate_certs: no

- name: Check For Jenkins List    
  stat: path=/etc/apt/sources.list.d/jenkins.list
  register: jenkins_list

- name: Adding Jenkins Source List
  become: yes
  lineinfile:
    path: /etc/apt/sources.list.d/jenkins.list
    line: deb http://pkg.jenkins.io/debian-stable binary/
    create: yes
  when: not jenkins_list.stat.exists

- name: Installing Jenkins
  become: yes
  apt:
    name: jenkins     
    state: present
    update_cache: yes
  register: jenkins_install

- name: Change port to 9000
  lineinfile: 
    dest=/etc/default/jenkins
    regexp=^HTTP_PORT=
    line=HTTP_PORT=9000
  become: true

- name: Restarting Jenkins
  become: yes
  service:
    name: jenkins
    state: restarted
  when: jenkins_install.changed

- name: "Wait For Jenkins To Come Up"
  uri:
    url: http://192.168.33.20:9000
    status_code: 403
  register: result
  until: result.status == 403
  retries: 6
  delay: 15
  when: jenkins_install.changed