- name: Get crumb request
  uri:
    url: '{{ jenkins_url }}/crumbIssuer/api/xml?xpath=concat(//crumbRequestField,":",//crumb)'
    user: '{{ jenkins_user }}'
    password: '{{ admin_pwd }}'
    force_basic_auth: yes
    return_content: yes
  register: crumb

- name: Copy the YAML to setup build job
  copy:
    src: /bakerx/pipeline/iTrust-pipeline.yml
    dest: /tmp/iTrust-pipeline.yml

- name: Setup database properties for the build job
  become: true
  lineinfile:
    path: /tmp/iTrust-pipeline.yml
    insertafter: cp db.properties.template db.properties
    line: "          sed 's/password /password {{ mysql_pwd }}/g' db.properties > new && mv new db.properties"
    state: present

- name: Setup database properties for the build job
  become: true
  lineinfile:
    path: /tmp/iTrust-pipeline.yml
    insertafter: cp email.properties.template email.properties
    line: "          sed 's/from /from {{ smtp_from }}/g;s/username /username {{ smtp_username }}/g;s/password /password {{ smtp_password }}/g' email.properties > new && mv new email.properties'''"
    state: present

- name: Create the build job in jenkins
  command: jenkins-jobs update /tmp/iTrust-pipeline.yml
