---
- name: Add java repo
  become: yes
  apt_repository: repo='ppa:openjdk-r/ppa'

- name: apt update
  become: yes
  apt:
    upgrade: yes
    update_cache: yes

- name: install openjdk
  become: yes
  apt:
    name: openjdk-11-jdk
    state: present

- name: Set timezone to America/New_York
  become: yes
  timezone:
    name: America/New_York
