---
# Copy the files from ansible onto jenkins

- name: Copy the Fuzzer class file to jenkins-srv
  copy:
    src: /bakerx/pipeline/fuzzer.js
    dest: fuzzer.js

- name: Copy driver js code for test prioritization analysis
  copy:
    src: /bakerx/pipeline/mutation_driver.js
    dest: mutation_driver.js

- name: Copy script for configuring iTrust repository
  copy:
    src: /bakerx/pipeline/email-db-config.sh
    dest: email-db-config.sh

- name: Change script to an executable
  file:
    path: email-db-config.sh
    mode: '0700'

- name: Copy script for deleting iTrust repository
  copy:
    src: /bakerx/pipeline/cleanup-iTrust.sh
    dest: cleanup-iTrust.sh

- name: Change script to an executable
  file:
    path: cleanup-iTrust.sh
    mode: '0700'

- name: Copy package.json 
  copy:
    src: /bakerx/package.json
    dest: package.json

- name: Install required node packages
  shell: npm install

- name: Setup MySQL Configurations
  copy:
    dest: "mysql_config.txt"
    content: |
      [client]
      user={{ mysql_user }}
      password={{ mysql_pwd }}

- name: Add the gmail credentials to env vars
  become: yes
  blockinfile:
    path: /etc/environment
    marker: '## GMAIL ENV VARIABLES'
    block: |
      SMTP_USERNAME={{ smtp_username }}
      SMTP_FROM={{ smtp_from }}
      SMTP_PASSWORD={{ smtp_password }}